name: Backend | Build → TAR → Upload(artifact) → Notify infra
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  SERVICE: backend
  IMAGE_NAME: carnav-backend
  INFRA_REPO: gabriella0128/career-navigator-infra

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (선택) 사전 빌드/테스트: Dockerfile이 자체 빌드하면 생략 가능
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: ./gradlew bootJar --no-daemon

      - name: Set TAG
        id: meta
        run: echo "TAG=main-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Docker build
        run: |
          docker build -t $IMAGE_NAME:${{ steps.meta.outputs.TAG }} -t $IMAGE_NAME:latest .

      - name: Save image as TAR
        run: |
          mkdir -p /tmp/carnav
          docker save -o /tmp/carnav/${{ env.SERVICE }}-${{ steps.meta.outputs.TAG }}.tar \
            $IMAGE_NAME:${{ steps.meta.outputs.TAG }}

      - name: Upload artifact (TAR)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERVICE }}-image-${{ steps.meta.outputs.TAG }}     # ← 아티팩트 이름
          path: /tmp/carnav/${{ env.SERVICE }}-${{ steps.meta.outputs.TAG }}.tar
          retention-days: 7

      - name: Notify infra (repository_dispatch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v3
        with:
          token:      ${{ secrets.INFRA_REPO_TOKEN }}
          repository: ${{ env.INFRA_REPO }}
          event-type: deploy
          client-payload: |
            {
              "service": "backend",
              "tag": "${{ steps.meta.outputs.TAG }}",
              "repo": "${{ github.repository }}",
              "run_id": "${{ github.run_id }}",
              "artifact_name": "backend-image-${{ steps.meta.outputs.TAG }}",
              "image_name": "carnav-backend"
            }
